name: Compile with SourceMod

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sm_version: ["1.11", "1.12"]


    steps:
      - uses: actions/checkout@v1

      - name: Set environment variables
        run: |
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          echo "SOURCEMOD_PATH=$SOURCEMOD_PATH" >> $GITHUB_ENV
          echo "SCRIPTING_PATH=$SOURCEMOD_PATH/scripting" >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Compile plugin
        run: |
          echo -e "\nCompiling test_compile.sp..."
          spcomp -E -w234 -O2 -v2 -i$includePath -i$SCRIPTING_PATH/include test_compile.sp
        working-directory: ${{ env.SCRIPTING_PATH }}/tests
